# Generated by Django 4.2.3 on 2023-07-30 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ask_help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ask_help',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_ask_help',
            name='expert_id',
            field=models.CharField(max_length=60),
        ),
    ]
