# Generated by Django 4.2.3 on 2023-07-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ask_help', '0002_customer_ask_help_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_ask_help',
            name='problem_discription',
        ),
    ]
