# Generated by Django 4.2.3 on 2023-07-30 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ask_help', '0003_remove_customer_ask_help_problem_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ask_help',
            name='customer_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
