# Generated by Django 4.2.3 on 2023-07-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ask_help', '0004_customer_ask_help_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_ask_help',
            name='name',
        ),
    ]
