# Generated by Django 4.2.3 on 2023-07-31 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_ask_help', '0005_remove_customer_ask_help_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ask_help',
            name='problem_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
