# Generated by Django 4.2.3 on 2023-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_information',
            fields=[
                ('customer_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, default='image/customer.png', null=True, upload_to='customer/image/')),
            ],
        ),
    ]
