# Generated by Django 4.2.3 on 2023-07-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_verfication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_verfication',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
