# Generated by Django 4.2.3 on 2023-07-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_verfication', '0003_remove_task_verfication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_verfication',
            name='expert_id',
            field=models.CharField(max_length=60),
        ),
    ]
