# Generated by Django 4.2.3 on 2023-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertid', models.CharField(max_length=40)),
                ('work_areas', models.CharField(max_length=40)),
                ('expert_in', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=40)),
            ],
        ),
    ]
