# Generated by Django 4.2.3 on 2023-07-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('roll', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, default='image/customer.png', null=True, upload_to='customer/image/')),
            ],
        ),
    ]
