# Generated by Django 4.2.3 on 2023-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('phonenumber', models.CharField(max_length=40)),
                ('education', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, default='/experts.png', null=True, upload_to='')),
            ],
        ),
    ]
