# Generated by Django 4.2.3 on 2023-07-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_tr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user_it',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tr',
        ),
    ]
