# Generated by Django 4.2.3 on 2023-07-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_rename_user_id_message_user_it_remove_message_tr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_it',
            new_name='user_id',
        ),
    ]
