# Generated by Django 4.2.3 on 2023-10-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_user_it_message_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(),
        ),
    ]
